jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsadOtherSymbo$'

server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/getarraycourse
    password: 323226
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
   